In [1]:
import numpy as np

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Perform an operation on the array
double = array * 2

print(double)  # Outputs: array([2, 4, 6, 8, 10])

[ 2  4  6  8 10]


In [2]:
# Creating an array in NumPy
array = np.array([1, 2, 3])
print(array)

[1 2 3]


In [3]:
import numpy as np

# Create a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Check properties of the array
print(array_1d.ndim)  # Output: 1
print(array_1d.shape)  # Output: (5,)
print(array_1d.size)  # Output: 5
print(array_1d.dtype)  # Output: int64

1
(5,)
5
int32


In [4]:
# Create a 2D array from a list of lists
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
# Output: 
# [[1 2 3]
#  [4 5 6]]

# Create a 2D array of zeros with shape (3, 2)
zeros = np.zeros((3, 2))
print(zeros)
# Output: 
# [[0. 0.]
#  [0. 0.]
#  [0. 0.]]

[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
# Create a float type array
float_array = np.array([1.0, 2.0, 3.0])
print(float_array.dtype)  # Output: float64

float64


In [11]:
initialised_array = np.zeros((5,5))
print(initialised_array)

initialised_array1 = np.ones((5,5))
print(initialised_array1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
data_2d = np.array([[50,40,30],[2,3,5],[77,55,33]])
print(data_2d)
sliced_array=data_2d[1:,1:]
print(sliced_array)

[[50 40 30]
 [ 2  3  5]
 [77 55 33]]
[[ 3  5]
 [55 33]]


In [15]:
marks=np.array([1,2,3,4,5,6])
reversed= marks[::-1]
print(reversed)

[6 5 4 3 2 1]


In [17]:
ids=np.arange(10)
print(ids)

ids=np.arange(10,21)
print(ids)

ids=np.arange(0,11,2)
print(ids)


[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10]


In [19]:
loto=np.linspace(0,40,9)
print(loto)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40.]


In [34]:
random=np.random.rand(1,10,5)
print(random)

[[[0.65230104 0.28500029 0.35638563 0.96468212 0.28421815]
  [0.65544412 0.69200395 0.95268398 0.13626056 0.73273944]
  [0.75811763 0.57365556 0.70780033 0.26074903 0.099096  ]
  [0.37154036 0.37478431 0.28620108 0.96338051 0.79090846]
  [0.19427077 0.3150091  0.19560718 0.80943548 0.03920405]
  [0.4097075  0.72776191 0.55201643 0.88018205 0.19931061]
  [0.79898624 0.49503665 0.64464815 0.50457936 0.69345999]
  [0.88430325 0.78398106 0.94030916 0.72733944 0.8670873 ]
  [0.96576269 0.21509182 0.60257833 0.3642533  0.31268737]
  [0.99456946 0.73891081 0.84751366 0.02484233 0.58292344]]]


In [37]:
x=np.zeros((2,3))
print(x)

reshape=np.reshape(x,(3,2))
print(reshape)
reshape=np.reshape(x,(1,6))
print(reshape)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]]


In [38]:
# Define an array
array = np.array([0, 2, 2, 6, 5])

# Use bincount
count = np.bincount(array)
print(count)
# Output: [1 0 2 0 0 1 1]

[1 0 2 0 0 1 1]
